In [1]:
import pandas as pd
import ndjson
import ijson
import os

In [3]:
with open('RS_2020-04') as f:
    reader = ndjson.reader(f)
    done_posts = {}
    done_posts['post_id'] = []
    done_posts['author_id'] = []
    done_posts['author'] = []
    done_posts['subreddit_id'] = []
    done_posts['subreddit'] = []
    done_posts['created_utc'] = []
    done_posts['num_comments'] = []
    done_posts['num_crossposts'] = []
    done_posts['nsfw'] = []
    done_posts['score'] = []
    done_posts['title'] = []
    done_posts['is_video'] = []
    done_posts['has_image'] = []
    done_posts['total_awards_received'] = []
    done_posts['is_part_of_collection'] = []
    done_posts['is_self_post'] = []
    
    for post in reader:
        done_posts['post_id'].append(post["id"])
        try:
            done_posts['author_id'].append(post["author_fullname"])
        except KeyError:
            done_posts['author_id'].append("")
        try:
            done_posts['author'].append(post["author"])
        except KeyError:
            done_posts['author'].append("")
        done_posts['subreddit_id'].append(post["subreddit_id"])
        done_posts['subreddit'].append(post["subreddit"])
        done_posts['created_utc'].append(post["created_utc"])
        done_posts['num_comments'].append(post["num_comments"])
        done_posts['num_crossposts'].append(post["num_crossposts"])
        done_posts['nsfw'].append(post["over_18"])
        done_posts['score'].append(post["score"])
        done_posts['title'].append(post["title"])
        done_posts['is_video'].append(post["is_video"])
        try:
            if post["thumbnail"] == "image":
                done_posts['has_image'].append(True)
            else:
                done_posts['has_image'].append(False)
        except KeyError:
            done_posts['has_image'].append(False)
        done_posts['total_awards_received'].append(post["total_awards_received"])
        try:
            done_posts['is_part_of_collection'].append([collection['collection_id'] for collection in post['collections']])
        except KeyError:
            done_posts['is_part_of_collection'].append([])
        done_posts['is_self_post'].append(post["is_self"])
        
dataset = pd.DataFrame.from_dict(done_posts)
#Elimino i post senza autore
dataset = dataset.loc[dataset['author_id']>""]
print(len(dataset))
dataset.head()

23770219

,post_id,author_id,author,subreddit_id,subreddit,created_utc,num_comments,num_crossposts,nsfw,score,title,is_video,has_image,total_awards_received,is_part_of_collection,is_self_post
0,d1g7c8,t2_i3z6b,mlokm,t5_31us7,dailyverse,1585717210,0,0,False,1,April 2020 | What is the Relationship Between ...,False,False,0,[ba6ade9f-79ad-4f5e-ba1e-48d7e6b4c8f9],True
1,d1g7c8,t2_i3z6b,mlokm,t5_31us7,dailyverse,1585717210,0,0,False,1,April 2020 | What is the Relationship Between ...,False,False,0,[ba6ade9f-79ad-4f5e-ba1e-48d7e6b4c8f9],True
2,fb8ddv,t2_p1ywx,THEOILLUMINATI,t5_2rptq,EdmontonOilers,1585753209,0,0,False,1,The Morning After | Golden Knights v. Oilers,False,False,0,[],True
3,fkqaiw,t2_3qyf2d6f,IsraelNazir,t5_13qajw,ahl_al_Kitab,1585774809,0,0,False,1,Tao Te King - The message of our Book - Chapte...,False,False,0,[],True
4,fp3lcb,t2_9qf0f,NicholasCajun,t5_2xhxq,westworld,1585767611,394,0,False,129,"Westworld - 3x03 ""The Absence of Field"" - Mid-...",False,False,0,[],True

In [4]:
dataset.to_csv('dataset/apr.csv', index=False)

In [2]:
feb = pd.read_csv('dataset/feb.csv', header=0)
print('read feb')
mar = pd.read_csv('dataset/mar.csv', header=0)
print('read mar')
apr = pd.read_csv('dataset/apr.csv', header=0)
print('read apr')

read feb
read mar
read apr

TypeError: 'function' object is not subscriptable

In [3]:
complete_dataset = pd.concat([feb,mar,apr])
del feb
del mar
del apr
print('done concat')
complete_dataset.drop_duplicates(inplace=True)
print('done duplicates')
complete_dataset = complete_dataset.sort_values(by=['created_utc'])
print(len(complete_dataset))
complete_dataset.head()

done concat
done duplicates
62521691

,post_id,author_id,author,subreddit_id,subreddit,created_utc,num_comments,num_crossposts,nsfw,score,title,is_video,has_image,total_awards_received,is_part_of_collection,is_self_post
38,ewxgwo,t2_46zsxucy,Trashpotatolol,t5_n9nn1,Market76,1580515200,4,0,False,2,[XB1] H: Bloodied explosive lvc minigun W: Blo...,False,False,0,[],False
39,ewxgwr,t2_6vjwa,NBA_MOD,t5_2qo4s,nba,1580515200,380,0,False,20,GAME THREAD: Memphis Grizzlies (24-24) @ New O...,False,False,0,[],True
42,ewxgwu,t2_ud3bj,railwayman_99,t5_31mhn,SakuraGakuin,1580515200,5,0,False,27,Sakuraday 251 for all things SG related :o) (U...,False,False,0,[],True
37,ewxgwn,t2_7u6ka,scrumptiouscakes,t5_2qhyq,classicalmusic,1580515200,0,0,False,0,Gnif gnaf plif plof! The animal sounds of Clém...,False,False,0,[],False
36,ewxgwm,t2_162dnw,forlorn12345,t5_2dar36,China_Flu,1580515200,1,0,False,1,China sends planes to bring 'stranded' oversea...,False,False,0,[],False

In [4]:
complete_dataset.to_csv('dataset/dataset.csv', index=False)

In [4]:
authors = pd.read_csv('dataset/authors.csv', header=0)
authors.head()

     author_id            author   created_utc  is_gold  is_suspended   karma
0  t2_46zsxucy    Trashpotatolol  1.569138e+09    False         False     343
1     t2_6vjwa           NBA_MOD  1.328751e+09     True         False  102839
2     t2_ud3bj     railwayman_99  1.454452e+09    False         False    9309
3     t2_7u6ka  scrumptiouscakes  1.338287e+09    False         False   27132
4    t2_162dnw      forlorn12345  1.489119e+09    False         False   11406

In [5]:
dataset = pd.read_csv('dataset/dataset.csv', header=0)
dataset.head()

,post_id,author_id,author,subreddit_id,subreddit,created_utc,num_comments,num_crossposts,nsfw,score,title,is_video,has_image,total_awards_received,is_part_of_collection,is_self_post
0,ewxgwo,t2_46zsxucy,Trashpotatolol,t5_n9nn1,Market76,1580515200,4,0,False,2,[XB1] H: Bloodied explosive lvc minigun W: Blo...,False,False,0,[],False
1,ewxgwr,t2_6vjwa,NBA_MOD,t5_2qo4s,nba,1580515200,380,0,False,20,GAME THREAD: Memphis Grizzlies (24-24) @ New O...,False,False,0,[],True
2,ewxgwu,t2_ud3bj,railwayman_99,t5_31mhn,SakuraGakuin,1580515200,5,0,False,27,Sakuraday 251 for all things SG related :o) (U...,False,False,0,[],True
3,ewxgwn,t2_7u6ka,scrumptiouscakes,t5_2qhyq,classicalmusic,1580515200,0,0,False,0,Gnif gnaf plif plof! The animal sounds of Clém...,False,False,0,[],False
4,ewxgwm,t2_162dnw,forlorn12345,t5_2dar36,China_Flu,1580515200,1,0,False,1,China sends planes to bring 'stranded' oversea...,False,False,0,[],False

In [6]:
dataset2 = dataset.loc[dataset['author_id'].isin(list(authors['author_id']))]

True

In [3]:
dataset2.to_csv('dataset/dataset.csv', index=False)

In [2]:
subreddits = pd.read_csv('dataset/subreddits.csv', header=0)
dataset = pd.read_csv('dataset/dataset.csv', header=0)
dataset2 = dataset.loc[dataset['subreddit_id'].isin(list(subreddits['subreddit_id']))]
print(len(dataset2))
dataset2.head()

53438379

,post_id,author_id,author,subreddit_id,subreddit,created_utc,num_comments,num_crossposts,nsfw,score,title,is_video,has_image,total_awards_received,is_part_of_collection,is_self_post
0,ewxgwo,t2_46zsxucy,Trashpotatolol,t5_n9nn1,Market76,1580515200,4,0,False,2,[XB1] H: Bloodied explosive lvc minigun W: Blo...,False,False,0,[],False
1,ewxgwr,t2_6vjwa,NBA_MOD,t5_2qo4s,nba,1580515200,380,0,False,20,GAME THREAD: Memphis Grizzlies (24-24) @ New O...,False,False,0,[],True
2,ewxgwu,t2_ud3bj,railwayman_99,t5_31mhn,SakuraGakuin,1580515200,5,0,False,27,Sakuraday 251 for all things SG related :o) (U...,False,False,0,[],True
3,ewxgwn,t2_7u6ka,scrumptiouscakes,t5_2qhyq,classicalmusic,1580515200,0,0,False,0,Gnif gnaf plif plof! The animal sounds of Clém...,False,False,0,[],False
4,ewxgwm,t2_162dnw,forlorn12345,t5_2dar36,China_Flu,1580515200,1,0,False,1,China sends planes to bring 'stranded' oversea...,False,False,0,[],False